LOCAL_PATH := $(call my-dir)

$(call add-radio-file,dpm.img)
$(call add-radio-file,gz.img)
$(call add-radio-file,lk.img)
$(call add-radio-file,logo.img)
$(call add-radio-file,mcupm.img)
$(call add-radio-file,md1img.img)
$(call add-radio-file,preloader_raw.img)
$(call add-radio-file,pi_img.img)
$(call add-radio-file,scp.img)
$(call add-radio-file,spmfw.img)
$(call add-radio-file,sspm.img)
$(call add-radio-file,tee.img)